ServerTokens Prod
ServerSignature Off

# mod_security: remove Server header completely
SecServerSignature " "
SecRuleEngine Off

Header always unset X-Powered-By
Header always set X-Content-Type-Options "nosniff"
