services:

  app:
    build:
      context: resources/data/apache
    container_name: ${APP_NAME:-flames}-app
    restart: unless-stopped
    volumes:
      - ../../../:/var/www/html
    ports:
      - "${APP_FORWARDED_PORT:-8080}:${APP_PORT:-80}"
    depends_on:
      - php-flames-ready
    networks:
      - flames

  db:
    image: mysql:8.0
    container_name: ${APP_NAME:-flames}-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MARIADB_PASSWORD:-root}
      MYSQL_DATABASE: ${DATABASE_MARIADB_NAME:-flames}
      MYSQL_USER: ${DATABASE_MARIADB_USER:-flames}
      MYSQL_PASSWORD: ${DATABASE_MARIADB_PASSWORD:-root}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./resources/data/mysql/my.cnf:/etc/mysql/conf.d/flames.cnf
    ports:
      - "${DATABASE_MARIADB_PORT:-3308}:3306"
    networks:
      - flames

  php-flames-ready:
    build:
      context: resources
      dockerfile: data/php-flames-ready/Dockerfile
    container_name: ${APP_NAME:-flames}-php-flames-ready
    restart: unless-stopped
    command: ["php", "/var/www/html/index.php"]
    volumes:
      - ../../../:/var/www/html
    depends_on:
      - db
    networks:
      - flames

#  php-fpm:
#    build:
#      context: resources/data/php-fpm
#    container_name: ${APP_NAME:-flames}-php-fpm
#    restart: unless-stopped
#    volumes:
#      - ../../../:/var/www/html
#    depends_on:
#      - db
#    networks:
#      - flames

networks:
  flames:
    driver: bridge

volumes:
  mariadb_data:
