[www]
listen = /run/php/php8.5-fpm.sock
listen.mode = 0666

pm = static
pm.max_children = 16
pm.max_requests = 10000

request_terminate_timeout = 300s

php_admin_value[memory_limit] = 256M
php_admin_flag[log_errors] = on
